
// This file has been generated by the GUI designer. Do not modify.
namespace vsts
{
	public partial class StandardChooserControl
	{
		private global::Gtk.HBox hbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget vsts.StandardChooserControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "vsts.StandardChooserControl";
			// Container child vsts.StandardChooserControl.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
