
// This file has been generated by the GUI designer. Do not modify.
namespace vsts
{
	public partial class TrafficView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget vsts.TrafficView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "vsts.TrafficView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
